runtime: python312

# [START handlers]
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /assets
  static_dir: assets
  
- url: /images
  static_dir: images
  
- url: /.*
  script: auto
# [END handlers]

# Environment variables
env_variables:
  FLASK_ENV: production
